### PR TITLE
Restore original user and group IDs after jattach operation

### PR DESCRIPTION
**Pull request by xuing**
Restore original user and group IDs after jattach operation

### CODE REVIEW

**Comment by apangin** [comment]
Please elaborate on the problem you're trying to solve.
Pull requests without a detailed description are unlikely to be accepted.

**Comment by deadok22** [comment]
I don't know what the author's use-case is, but I have one that may be addressed by this patch.

In my setup, `jattach` is started by `sudo`, which is in turn run by a controlling process that is unprivileged. The controlling process fails to send signals to `jattach` because:
```
$ man 2 kill | grep -A 4 'For  a  process  to  have  permission' 
       For  a  process  to  have  permission  to  send a signal, it must either be privileged (under Linux: have the
       CAP_KILL capability in the user namespace of the target process), or the real or effective  user  ID  of  the
       sending  process  must equal the real or saved set-user-ID of the target process.  In the case of SIGCONT, it
       suffices when the sending and receiving processes belong to the same session.  (Historically, the rules  were
       different; see NOTES.)
```
Restoring the ids may make it possible for the controlling process to send signals to `jattach` in my setup.

**Comment by xuing** [comment]
> Please elaborate on the problem you're trying to solve. Pull requests without a detailed description are unlikely to be accepted.

My apologies for initially lacking detailed context. In my unique scenario, I use jattach in an FFI context, often requiring dynamic attachment to multiple JVM processes. When these processes are not under a privileged account, it's important to restore the original user ID (uid) and group ID (gid) after the jattach operation to prevent permission issues in my main program.

**Comment by apangin** [comment]
Yeah, I thought the idea was to reverse the process level changes made by jattach. Although your proposed changes may help in some cases, the solution is incomplete and will not work elsewhere. Besides just switching euid/egid, jattach does other things like changing signal handler and switching to the target process' namespaces. The latter is not easily reversible.

The right solution would be to fork before calling jattach. This will ensure all changes made by jattach will not affect the parent process. For instance, that's exactly how [async-profiler](https://github.com/async-profiler/async-profiler/blob/3c33c755be9f4f55d94699bf5ac0ff9ed2e4e4f1/src/launcher/main.cpp#L336-L358) uses jattach.

**Comment by xuing** [comment]
Thanks for your guidance. I understand the right approach now.

**Pull request closed without merging**
